services:
  yafi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/yafi
      - SPRING_DATA_REDIS_HOST=redis

  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yafi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d yafi" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

