spring.output.ansi.enabled=ALWAYS

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.open-in-view=false

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/yafi
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=root
spring.datasource.password=root

logging.level.org.springframework.web=ERROR
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=ERROR

spring.jpa.show-sql=true

server.port = 8080

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always




